name: SecondaryAuthentication-Bukkit
version: 1.0.0
main: live.amsleepy.secondaryauthenticationbukkit.SecondaryAuthentication_Bukkit
api-version: 1.13
description: Acts as a 2nd layer of protection on top of authentication plugins for server staffs

commands:
  login:
    description: Login command
  verify:
    description: Verify yourself
    usage: /verify <secret code>
  secondaryauthentication:
    description: Manage SecondaryAuthentication plugin
    aliases: [secauth]
    usage: /secondaryauthentication reload
permissions:
  secondaryauthentication.reload:
    description: Allows the user to reload the SecondaryAuthentication plugin.
    default: op